### ISSUE TITLE
bugs with new version of skmultiflow，can you provide the version of skmultiflow which you use in this project？thanks！

### ISSUE THREAD

**Issue by Sherlock1118** [AminMe/ARF#1]
bugs with new version of skmultiflow，can you provide the version of skmultiflow which you use in this project？thanks！

**Comment by messaoudia** [comment]
Hi @Sherlock1118 i will suggest you to use a version of `sckikit-multiflow` that has been published before `12 Feb 2018` which is the date where we committed the code on GitHub if you want to make this code works.

Unfortunately on Pypi (https://pypi.org/project/scikit-multiflow/#history) I do not see a version before that date. 

I suggest you to try first to install the version 0.1.0 to try this out. Or to go to their Github project and install a version that is close to the date I gave you before (you can find this: https://scikit-multiflow.readthedocs.io/en/stable/installation.html#option-1-install-from-source-code)

Btw what is the error ? Maybe you can track it and find a fix

**Comment by asmaafawzy25** [comment]
Hi @messaoudia,

I also have an error like this
 File "c:/Users/Asmaa/OneDrive/Documents/GitHub/AdaptiveRandomForest/src/Execution.py", line 1, in <module>
    from skmultiflow.classification.trees.hoeffding_tree import HoeffdingTree
ModuleNotFoundError: No module named 'skmultiflow.classification'
 how can I fix it, I used this command ti install scikit-multiflow
pip install -U git+https://github.com/scikit-multiflow/scikit-multiflow

Many Thnx

**Comment by messaoudia** [comment]
You have 2 options:
* Install version 0.1.0 of sckikit-multiflow `pip install sckikit-multiflow==0.1.0`
* Use the latest version of and update the code of this repo locally and then use the new path to import the algorithms. Maybe this will help: https://github.com/scikit-multiflow/scikit-multiflow/issues/105

**Comment by messaoudia** [comment]
Cf. https://github.com/messaoudia/AdaptiveRandomForest/issues/3#issuecomment-1067827222
