### ISSUE TITLE
An error with this project

### ISSUE THREAD

**Issue by asmaafawzy25** [AminMe/ARF#2]
Dear @messaoudia 

when I use your project I found this bug when executing the Execution.py file
 _File "c:/Users/Asmaa/OneDrive/Documents/GitHub/AdaptiveRandomForest/src/Execution.py", line 1, in <module>
    from skmultiflow.classification.trees.hoeffding_tree import HoeffdingTree
ModuleNotFoundError: No module named 'skmultiflow.classification'_

although I installed the skmultiflow, how can I fix this bug?

Thank You

**Comment by messaoudia** [comment]
Hi
Check https://github.com/messaoudia/AdaptiveRandomForest/issues/1#issuecomment-846870914

**Comment by asmaafawzy25** [comment]
thnx for the reply :)

**Comment by messaoudia** [comment]
Cf. https://github.com/messaoudia/AdaptiveRandomForest/issues/3#issuecomment-1067827222
