### ISSUE TITLE
There are still bugs with v0.1.0 version of skmultiflow，could you provide the skmultiflow packet file you used？thanks！

### ISSUE THREAD

**Issue by ywang-art** [AminMe/ARF#3]
![(NR3ZB_W5PQZ( S~8$ {S_J](https://user-images.githubusercontent.com/80510097/158349376-37199d01-bfac-4dfd-bdf5-a46d947ebf85.png)

**Comment by messaoudia** [comment]
Hi @ywang-art 

I suggest you to use last version of scikit-multiflow which is `0.5.3` ([link](https://pypi.org/project/scikit-multiflow/#history)) which is btw already 2 years old
To be honnest I can't remember which version we used, and its not a good idea to use an old not optimised version of the code. Meanwhile the lib has not been updated for 2 years which is not a really good sign !

Anyway the best thing to do for you is to use the new project structure.
For instance `GaussianNumericAttributeClass` has been renamed https://github.com/scikit-multiflow/scikit-multiflow/blob/master/src/skmultiflow/trees/_attribute_observer/numeric_attribute_class_observer_gaussian.py
And adapt also method names

Another [example](https://github.com/scikit-multiflow/scikit-multiflow/blob/master/src/skmultiflow/trees/hoeffding_tree.py):
`from skmultiflow.classification.trees.hoeffding_tree import HoeffdingTree`
is now `from skmultiflow.trees.hoeffding_tree import HoeffdingTree`

etc.

**Comment by messaoudia** [comment]
Also you have only 3 python files in this project
Updating imports could be fast

**Comment by nedRad88** [comment]
Hi @ywang-art ,

You should also take a look at river package [link](https://github.com/online-ml/river), which is the continuation of skmultiflow. That library is up-to-date.

**Comment by ywang-art** [comment]
> Also you have only 3 python files in this project Updating imports could be fast

OK， thank you very much for your advice!

**Comment by ywang-art** [comment]
> Hi @ywang-art ,
> 
> You should also take a look at river package [link](https://github.com/online-ml/river), which is the continuation of skmultiflow. That library is up-to-date.

Thank you very much for your advice. It helps me a lot!
